/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class TabConstants{
  static readonly DEF_FONT_WEIGHT: number = 400;

  static readonly SELE_FONT_WEIGHT: number = 800;

  static readonly LINE_START_COLOR: string = '#ff3d47e3';

  static readonly LINE_END_COLOR: string = '#FFF';

  static readonly DEF_FONT_COLOR: string = 'rgba(0, 0, 0, 0.6)';

  static readonly SELE_FONT_COLOR: string = 'rgb(10, 89, 247)';

  static readonly INDICATOR_WIDTH: number = 20;

  static readonly INDICATOR_HEIGHT: number = 2;

  static readonly TAB_ICON_WIDTH: number = 16;

  static readonly TAB_ICON_HEIGHT: number = 15;

  static readonly TAB_HEIGHT: number = 32;

  static readonly TAB_COL_HEIGHT: number = 96;
}
