/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonConstants } from '../constants/CommonConstants';
import { NavConstants } from '../constants/NavConstants';

@Component
export struct PageHeaderComp {
  @Prop title: ResourceStr;
  backAction: Function = () => {
  }

  build() {
    Stack() {
      Text(this.title)
        .fontSize(16)
        .fontWeight(400)
      Stack({ alignContent: Alignment.Start }) {
        Image($r('app.media.mi_ic_right_arrow'))
          .width(NavConstants.F_PIC_WIDTH)
          .height(NavConstants.F_PIC_WIDTH)
          .rotate({
            x: 0,
            y: 0,
            z: 1,
            centerX: '50%',
            centerY: '50%',
            angle: 180
          })
          .onClick(() => {
            this.backAction()
          })
      }.width(CommonConstants.COLUMN_WIDTH)
    }.width(CommonConstants.COLUMN_WIDTH)
    .padding(CommonConstants.MAIN_PADDING)
  }
}
