/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ShoppingMallConstants{
  static readonly ICON_WIDTH: number = 24;

  static readonly ICON_HEIGHT: number = 24;

  static readonly DOTINDICATOR_WIDTH: number = 6;

  static readonly SELE_DOTINDICATOR_WIDTH: number = 12;

  static readonly DOTINDICATOR_HEIGHT: number = 6;

  static readonly DOTINDICATOR_DEF_COLOR: string = '#57cccccc';

  static readonly DOTINDICATOR_SELE_COLOR: string = '#fff';

  static readonly SWIPER_HEIGHT: number = 300;

  static readonly HEADER_HEIGHT:number = 48;

  static readonly BOX_HEIGHT:number = 75;

  static TAB_WIDTH: number = 96;

  static readonly SELE_COLOR: string = '#fff';

  static readonly DEFA_COLOR: string = '#ff000';

  static readonly SELE_BG_COLOR: string = 'rgb(10, 89, 247)';

  static readonly DEFA_BG_COLOR: string = 'rgba(0, 0, 0, 0.05)';

  static readonly CHECKED_COLOR: string = '#941800f8';

  static readonly NOT_CHECKED_COLOR: string = '#ccc';

  static readonly LINE_COLOR: string = '#ffe2e2e2';

  static readonly SCROLL_hEIGHT: number = 80;
}
