/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class RecommendationConstants{
  static readonly DOTINDICATOR_WIDTH: number = 6;

  static readonly SELE_DOTINDICATOR_WIDTH: number = 12;

  static readonly DOTINDICATOR_HEIGHT: number = 6;

  static readonly DOTINDICATOR_DEF_COLOR: string = '#57cccccc';

  static readonly DOTINDICATOR_SELE_COLOR: string = '#fff';

  static readonly SWIPER_HEIGHT: number = 300;

  static readonly BOX_HEIGHT:number = 48;

  static readonly TOAST_HEIGHT:number = 136;
}
