/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ServiceConstants {
  static readonly SWIPER_HEIGHT: number = 300;
  static readonly TAB_COL_HEIGHT: number = 76;
  static readonly PUBLIC_SPACE: number = 12;
  static readonly LIST_SPACE: number = 10;
  static readonly DOTINDICATOR_WIDTH: number = 6;
  static readonly DOTINDICATOR_HEIGHT: number = 2;
  static readonly DOTINDICATOR_DEF_COLOR: string = '#ccc';
  static readonly DOTINDICATOR_SELE_COLOR: string = '#fff';
  static readonly FONT_WEIGHT: number = 600;
  static readonly PIC_WIDTH: number = 24;
  static readonly PIC_HEIGHT: number = 24;
  static readonly F_PIC_WIDTH: number = 18;
  static readonly F_PIC_HEIGHT: number = 18;
  static readonly S_PIC_WIDTH: number = 10;
  static readonly S_PIC_HEIGHT: number = 10;
  static readonly PADDING: number = 16;

  static readonly TEXT_INPUT_HEIGHT: number = 32;

  static readonly TEXT_PLACEHOLDER_COLOR:string = '#ffbcbbbb';
}