/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class TabConstants{
  static readonly TAB_ICON_WIDTH: number = 24;
  static readonly TAB_ICON_HEIGHT: number = 24;

  static readonly DEF_COLOR: string = '#999';

  static readonly SELE_COLOR: string = 'rgb(10, 89, 247)';

  static readonly TAB_BAR_L_WIDTH: number = 96;

  /**
   * Tab height.
   */
  static readonly TAB_BAR_L_HEIGHT: string = '50%';

  /**
   * Tab bar height.
   */
  static readonly TAB_BAR_HEIGHT: string = '100%';

  static readonly TAB_BAR_M_HEIGHT: number = 56;
}
